## MLX Core

### Arrays

#### Initialization and Types
- Creating arrays with `zeros`, `ones`, `full`, `arange`, etc.
- Data types (`float32`, `int64`, etc.) and type casting
- Integration with NumPy/PyTorch-style APIs

#### Architecture-Specific Traits
- Device-aware computation and memory layout




In [53]:
import mlx.core as mx
import numpy as np
import torch

In [60]:


#Initializing
arr1 = mx.array([1,2,3,4],dtype = mx.int16)
arr2 = mx.array([5,6,7,8])
print(arr1+arr2)



#Ways of preforming operations functional or similar to numpy


#Streaming specific operations





AttributeError: 'array' object has no attribute 'dotprod'

#### Indexing
- Basic slicing and indexing
- Advanced indexing and broadcasting
- Boolean masks and conditional selection

#### Saving Arrays
- Saving and loading with `mlx.savez`, `mlx.loadz`, etc.
- File formats and serialization

In [26]:

# Create a sample 3x3 array
x = mx.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

# Slicing
print(x[:, 1])         # All rows, column 1 → [20, 50, 80]
print(x[1:, :2])       # Rows 1 and 2, columns 0 and 1






array([20, 50, 80], dtype=int32)
array([[40, 50],
       [70, 80]], dtype=int32)
{'x': array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)}


### More Operations and Function Transforms

#### More Element-wise Operations
- Functions: `mx.exp`, `mx.log`, `mx.sqrt`, `mx.sin`, `mx.abs`, etc.
- Clipping: `mx.clip(x, min, max)`

#### Reductions
- Sum: `mx.sum(x, axis=...)`
- Mean: `mx.mean(x, axis=...)`
- Standard deviation `mx.std(x)`

#### Functional Transforms
- Gradients: `mx.grad(fn)` and `mx.value_and_grad(fn)`
- Vectorization: `mx.vmap(fn)` for applying a function over a batch

#### Type Utilities
- Type conversion: `x.astype(mx.float32)` etc.

In [35]:


#Example operations


numbers = mx.arange(7)+1
i = 3
print(f'Factorials {numbers.cumprod()}')


# Cosine of evenly spaced multiples of pi
pies = mx.pi * mx.arange(8)
print("Cosine of linear multiples of π:", mx.cos(pies))



# First derivative of log(x) is 1/x
inv = mx.grad(mx.log)
x_val = mx.array(1 / 10, dtype=mx.float32)
print("1 / 0.1 =", inv(x_val))  # Should be ~10.0


# Apply 1/x to an array using vmap (skip 0 to avoid division by zero)
v_inv = mx.vmap(inv)
x_no_zero = x[1:].astype(mx.float16)
print("1 / x for x = 1 to 10:", v_inv(x_no_zero))

# Second derivative of log(x): d/dx (1/x) = -1/x^2
inv_prime = mx.grad(inv)
x_10 = mx.array(10, dtype=mx.float32)
print("Derivative of 1/x at x = 10 (should be ~ -0.01):", inv_prime(x_10))

1 / x for x = 1 to 10: array([2147483647, 1, 0, ..., 0, 0, 0], dtype=int32)
Derivative of 1/x at x = 10 (should be ~ -0.01): array([-1, -0.25, -0.111084, ..., -0.015625, -0.0123444, -0.0100021], dtype=float16)



#### Shape Transformations
- Reshape: `mx.reshape(x, new_shape)`
- Transpose: `mx.transpose(x, axes=...)`
- Expand dims / Squeeze: `mx.expand_dims`, `mx.squeeze`
- Concatenate: `mx.concatenate([x, y], axis=...)`
- Stack/Unstack: `mx.stack`

In [78]:
x = mx.array([[1,2,3],[4,5,6],[7,8,9]], dtype = mx.float16)


x = mx.expand_dims(x,axis = 2)


arr1 = mx.array([1,2,3])
arr2 = mx.array([4,5,6])
arr3 = mx.array([7,8,9])
stack = mx.stack([arr1,arr2,arr3])
print(stack)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)


#### Linear Algebra (most operations are only suported on the cpu)
- Matrix Multiplication: `mx.matmul(x,y)` (*supported on gpu)
- Inverse: `mx.linalg.inverse(x)`
- Eigenvalues: `mx.linalg.eigvals(x)`
- Solution: `mx.linalg.solve(x)`

In [30]:
### Matrix Inversion and Linear Algebra in MLX

import mlx.core as mx

# Define a 2x2 matrix
A = mx.array([[4, 7],
              [2, 6]], dtype=mx.float32)

# Define the 2x2 identity matrix
I_2 = mx.array([[1, 0],
              [0, 1]], dtype=mx.float32)

# Identity Check: A * I == A
print("A * I == A:", mx.all(A == A @ I_2).item())

# Inverse of A (executed on CPU)
A_inv = mx.linalg.inv(A, stream=mx.cpu)
print("Inverse of A:\n", A_inv)

# Eigenvalues and Eigenvectors (on CPU)
eigvals = mx.linalg.eigvals(A, stream=mx.cpu)
eigvecs = mx.linalg.eigh(A, stream=mx.cpu)
print("Eigenvalues of A:\n", eigvals)
print("Eigenvectors of A:\n", eigvecs)

# Solving Ax = x_input
x_input = mx.array([11, 8], dtype=mx.float32)
solution = mx.linalg.solve(A, x_input, stream=mx.cpu)
print("Solution to Ax = x_input:\n", solution)



Solution to Ax = x_input:
 array([1, 1], dtype=float32)


#### Random

MLX provides a set of random utilities through `mx.random` for generating synthetic data or initializing parameters.



In [ ]:


# Normal distribution(default parameters:mean=0, std=1): 
normal_sample = mx.random.normal(shape=(3, 20))
print("Normal Sample:\n", normal_sample)

# Uniform distribution(default range [0.0, 1.0)): 
uniform_sample = mx.random.uniform(shape=(2, 4))
print("Uniform Sample:\n", uniform_sample)

# Set a random seed for reproducibility
mx.random.seed(123)

# Integer sampling with numpy (for discrete labels, etc.)
random_ints = mx.random.randint(low=0, high=10, shape=(2, 3))
print("Random Integers:\n", random_ints)



Normal Sample:
 array([[-0.0508169, -0.0931067, -1.01645, ..., 1.863, -0.449933, 1.01031],
       [0.166746, -1.57743, -1.34337, ..., -0.71716, 1.34559, 0.627446],
       [0.516814, 0.204601, -1.56062, ..., 1.11553, -1.98048, -1.21891]], dtype=float32)
Uniform Sample:
 array([[0.180577, 0.680501, 0.0474317, 0.0760371],
       [0.254368, 0.00757401, 0.0902404, 0.207927]], dtype=float32)
Random Integers:
 array([[0, 1, 1],
       [6, 8, 9]], dtype=int32)
tensor([1, 2, 3])
